markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile','README.md']
host: http://www.hervefalciani.com
baseurl: ""

name: Herve Falciani
description: Herve Falciani news and latest posts. Whistle blower.

paginate: 5

gems:
 - jekyll-sitemap
