markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile','README.md']
baseurl: http://www.hervefalciani.com

name: Herve Falciani
description: Herve Falciani news and latest posts. Whistle blower.

disqus: ajinkyax

paginate: 5